### ISSUE TITLE
Update repo to new charon folder structure

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon-distributed-validator-cluster#96]
## Problem to be solved

The directory structure output from `create cluster` command changed recently with this [PR](https://github.com/ObolNetwork/charon/pull/1532).

## Proposed Solution

Update this repo to use the new directory structure. For each `node[i]` charon service, add another env. For example, for node1, it would look like:
```
  node1:
    <<: *node-base
    environment:
      <<: *node-env
      CHARON_PRIVATE_KEY_FILE: /opt/charon/.charon/cluster/node1/charon-enr-private-key
      CHARON_LOCK_FILE: /opt/charon/.charon/cluster/node1/cluster-lock.json
      CHARON_JAEGER_SERVICE: node1
      CHARON_P2P_EXTERNAL_HOSTNAME: node1
```
And remove `CHARON_LOCK_FILE` from `x-node-env`.

Also, update the [docs](https://github.com/ObolNetwork/obol-docs) repo with new instructions.

## Out of Scope

None. But, this should be done before the next charon release (`v0.13.0`) is cut out. See [releases](https://github.com/ObolNetwork/charon/releases)
